import { StyleSheet } from 'react-native';

import type { AppPalette } from '@/constants/app-palette';

export function createEnterpriseDetailStyles(c: AppPalette) {
  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: c.background },
    scroll: { paddingBottom: 48, flexGrow: 1 },
    center: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 24,
      gap: 12,
      backgroundColor: c.background,
    },
    muted: { color: c.textMuted, marginTop: 8 },
    errTitle: { fontSize: 15, color: c.error, textAlign: 'center', fontWeight: '700' },
    retry: {
      marginTop: 8,
      backgroundColor: c.primary,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 12,
    },
    retryText: { color: c.onPrimary, fontWeight: '800' },
    heroWrap: {
      height: 220,
      backgroundColor: c.surfaceMuted,
    },
    heroImg: { width: '100%', height: '100%' },
    heroPh: { alignItems: 'center', justifyContent: 'center' },
    heroTop: {
      position: 'absolute',
      left: 0,
      right: 0,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      zIndex: 10,
    },
    iconBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    heroBadge: {
      position: 'absolute',
      left: 16,
      bottom: 16,
      backgroundColor: c.surfaceElevated,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: c.border,
    },
    heroBadgeText: { fontWeight: '800', color: c.primary, fontSize: 12 },
    block: { paddingHorizontal: 20, paddingTop: 18, gap: 10 },
    name: { fontSize: 26, fontWeight: '800', color: c.text },
    desc: { fontSize: 15, lineHeight: 22, color: c.textSecondary },
    infoRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
    infoText: { flex: 1, fontSize: 14, color: c.textMuted, lineHeight: 20 },
    sectionHead: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      marginTop: 24,
      marginBottom: 12,
    },
    sectionTitle: { fontSize: 18, fontWeight: '800', color: c.text },
    sectionHint: { fontSize: 13, color: c.textMuted },
    emptyProducts: {
      marginHorizontal: 20,
      padding: 24,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: 'center',
      gap: 10,
      backgroundColor: c.surfaceMuted,
    },
    emptyProductsText: { color: c.textMuted, textAlign: 'center', fontSize: 14 },
    productCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginHorizontal: 20,
      marginBottom: 12,
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surface,
    },
    productThumb: {
      width: 72,
      height: 72,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: c.surfaceMuted,
    },
    productImg: { width: '100%', height: '100%' },
    productImgPh: { alignItems: 'center', justifyContent: 'center' },
    galleryBadge: {
      position: 'absolute',
      right: 4,
      bottom: 4,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      paddingHorizontal: 6,
      paddingVertical: 3,
      borderRadius: 999,
      backgroundColor: 'rgba(0,0,0,0.55)',
    },
    galleryBadgeTxt: { color: '#FFF', fontSize: 11, fontWeight: '800' },
    productName: { fontSize: 16, color: c.text },
    productDesc: { fontSize: 13, color: c.textMuted, marginTop: 4 },
    productPrice: { fontSize: 15, fontWeight: '800', color: c.primary, marginTop: 6 },
    stock: { fontSize: 12, color: c.textMuted, marginTop: 4 },
    stockOut: { color: c.error, fontWeight: '700' },
    addBtn: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: c.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    addBtnDisabled: { backgroundColor: c.border, opacity: 0.85 },
  });
}
