import { Platform, StyleSheet } from 'react-native';

import type { AppPalette } from '@/constants/app-palette';

export function createMarketplaceStyles(c: AppPalette) {
  return StyleSheet.create({
    screen: { flex: 1 },
    scroll: { paddingHorizontal: 20 },
    searchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 14,
    },
    searchBar: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: Platform.OS === 'ios' ? 12 : 10,
      borderRadius: 12,
      backgroundColor: c.inputBg,
      borderWidth: 1,
      borderColor: c.inputBorder,
    },
    searchInput: {
      flex: 1,
      fontSize: 15,
      color: c.text,
      paddingVertical: 4,
    },
    filterBtn: {
      width: 48,
      height: 48,
      borderRadius: 12,
      backgroundColor: c.surface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: c.border,
    },
    segmentWrap: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 20,
    },
    segmentBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 12,
      borderRadius: 12,
      backgroundColor: c.surfaceMuted,
      borderWidth: 1,
      borderColor: c.border,
    },
    segmentBtnOn: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    segmentLabel: {
      fontSize: 15,
      fontWeight: '800',
      color: c.primaryDeep,
    },
    segmentLabelOn: {
      color: c.onPrimary,
    },
    loadingBox: {
      paddingVertical: 48,
      alignItems: 'center',
      gap: 12,
    },
    loadingText: { color: c.textMuted, fontSize: 14 },
    errorCard: {
      padding: 20,
      borderRadius: 12,
      backgroundColor: c.surfaceMuted,
      borderWidth: 1,
      borderColor: c.border,
      gap: 12,
      alignItems: 'center',
    },
    errorTitle: { color: c.textMuted, fontWeight: '600', textAlign: 'center' },
    retryBtn: {
      alignSelf: 'flex-start',
      backgroundColor: c.primary,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 12,
    },
    retryText: { color: c.onPrimary, fontWeight: '800' },
    sectionHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
      marginTop: 4,
    },
    sectionTitle: {
      fontSize: 15,
      fontWeight: '800',
      color: c.text,
    },
    seeAll: {
      fontSize: 13,
      fontWeight: '700',
      color: c.primary,
    },
    catScroll: {
      gap: 10,
      paddingBottom: 20,
      paddingRight: 8,
    },
    catItem: {
      alignItems: 'center',
      width: 76,
      gap: 6,
      paddingVertical: 8,
      paddingHorizontal: 4,
    },
    catItemOn: {},
    catIconWrap: {
      width: 52,
      height: 52,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    catCaption: {
      fontSize: 11,
      fontWeight: '600',
      color: c.textMuted,
      textAlign: 'center',
      lineHeight: 14,
      maxWidth: 72,
    },
    catEmpty: {
      fontSize: 13,
      color: c.textMuted,
      marginBottom: 16,
      paddingHorizontal: 4,
    },
    catLabel: {
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
      color: c.text,
      lineHeight: 18,
    },
    catLabelOn: {
      color: c.primaryDeep,
      fontWeight: '800',
    },
    popList: {
      gap: 10,
      marginBottom: 22,
    },
    popRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 12,
      borderRadius: 12,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
    },
    popRowPressed: { opacity: 0.94 },
    popThumb: {
      width: 80,
      height: 80,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: c.surfaceMuted,
    },
    popThumbImg: {
      width: '100%',
      height: '100%',
    },
    popThumbPh: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    popBody: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    popName: {
      fontSize: 16,
      color: c.text,
    },
    popMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexWrap: 'wrap',
    },
    popMeta: {
      fontSize: 13,
      color: c.textMuted,
      fontWeight: '600',
    },
    popDelivery: {
      fontSize: 12,
      fontWeight: '700',
      color: c.primary,
      marginTop: 2,
    },
    emptyHint: {
      paddingVertical: 16,
      paddingHorizontal: 12,
      marginBottom: 16,
    },
    emptyHintText: {
      fontSize: 13,
      color: c.textMuted,
      textAlign: 'center',
      lineHeight: 19,
    },
    productGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 22,
    },
    productCard: {
      backgroundColor: c.surface,
      borderRadius: 12,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: c.border,
      paddingBottom: 10,
    },
    productImgWrap: {
      aspectRatio: 1,
      backgroundColor: c.surfaceMuted,
      position: 'relative',
    },
    productImg: {
      width: '100%',
      height: '100%',
    },
    productImgPh: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    productName: {
      fontSize: 13,
      fontWeight: '700',
      color: c.text,
      paddingHorizontal: 10,
      marginTop: 8,
      minHeight: 36,
    },
    productPrice: {
      fontSize: 14,
      fontWeight: '800',
      color: c.primaryDeep,
      paddingHorizontal: 10,
      marginTop: 4,
    },
    productPriceWrap: {
      paddingHorizontal: 10,
      paddingBottom: 2,
    },
    promoRibbon: {
      position: 'absolute',
      top: 8,
      left: 8,
      zIndex: 2,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
    },
    promoRibbonText: {
      fontSize: 11,
      fontWeight: '800',
    },
    offerBanner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      padding: 16,
      borderRadius: 12,
      marginBottom: 8,
    },
    offerTitle: {
      color: c.onPrimary,
      fontSize: 17,
      fontWeight: '800',
      marginBottom: 6,
    },
    offerSub: {
      color: c.onPrimary,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '600',
      opacity: 0.92,
    },
  });
}
