-- =========================
-- EXTENSIONS (Supabase/PostgreSQL)
-- =========================
-- Supabase supporte pgcrypto; gen_random_uuid() est recommandé
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =========================
-- 1. ROLES
-- =========================
CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(20) UNIQUE
);

INSERT INTO roles (nom) VALUES ('client'), ('vendeur'), ('admin');

-- =========================
-- 2. UTILISATEURS
-- =========================
CREATE TABLE utilisateurs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nom VARCHAR(100),
    telephone VARCHAR(20) UNIQUE NOT NULL,
    mot_de_passe TEXT NOT NULL,
    image_url TEXT,
    role_id INT REFERENCES roles(id),
    cree_le TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- 3. OTP (authentification)
-- =========================
CREATE TABLE otp_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    telephone VARCHAR(20),
    code VARCHAR(10),
    expire_le TIMESTAMPTZ,
    valide BOOLEAN DEFAULT false
);

-- =========================
-- 4. ADRESSES
-- =========================
CREATE TABLE adresses_utilisateur (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    utilisateur_id UUID REFERENCES utilisateurs(id) ON DELETE CASCADE,
    libelle VARCHAR(50),
    adresse TEXT,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8)
);

-- =========================
-- 5. ENTREPRISES (livraison)
-- =========================
CREATE TABLE entreprises_livraison (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nom VARCHAR(150),
    telephone VARCHAR(20)
);

-- =========================
-- 6. LIVREURS
-- =========================
CREATE TABLE livreurs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entreprise_id UUID REFERENCES entreprises_livraison(id) ON DELETE SET NULL,
    nom VARCHAR(100),
    telephone VARCHAR(20),
    type_vehicule VARCHAR(50),
    disponible BOOLEAN DEFAULT true
);

-- =========================
-- 7. POSITIONS LIVREURS
-- =========================
CREATE TABLE positions_livreurs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    livreur_id UUID REFERENCES livreurs(id) ON DELETE CASCADE,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    enregistre_le TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- 8. ENTREPRISES (vendeurs)
-- =========================
CREATE TABLE entreprises (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proprietaire_id UUID REFERENCES utilisateurs(id) ON DELETE SET NULL,
    nom VARCHAR(150),
    type VARCHAR(20), -- boutique / restaurant
    description TEXT,
    telephone VARCHAR(20),
    adresse TEXT,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    ouvert BOOLEAN DEFAULT true
);

-- =========================
-- 9. HORAIRES
-- =========================
CREATE TABLE horaires_entreprise (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entreprise_id UUID REFERENCES entreprises(id) ON DELETE CASCADE,
    jour INT,
    ouverture TIME,
    fermeture TIME
);

-- =========================
-- 10. CATEGORIES
-- =========================
CREATE TABLE categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nom VARCHAR(100)
);

CREATE TABLE entreprises_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entreprise_id UUID REFERENCES entreprises(id) ON DELETE CASCADE,
    categorie_id UUID REFERENCES categories(id) ON DELETE CASCADE
);

-- =========================
-- 11. PRODUITS
-- =========================
CREATE TABLE produits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entreprise_id UUID REFERENCES entreprises(id) ON DELETE CASCADE,
    nom VARCHAR(150),
    description TEXT,
    prix DECIMAL(12,2),
    stock INT,
    image_url TEXT
);

-- =========================
-- 12. MENUS (restaurant)
-- =========================
CREATE TABLE menus (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    entreprise_id UUID REFERENCES entreprises(id) ON DELETE CASCADE,
    nom VARCHAR(150),
    description TEXT,
    prix DECIMAL(12,2),
    temps_preparation INT,
    disponible BOOLEAN DEFAULT true
);

-- =========================
-- 13. PANIER
-- =========================
CREATE TABLE paniers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    utilisateur_id UUID REFERENCES utilisateurs(id) ON DELETE CASCADE
);

CREATE TABLE panier_articles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    panier_id UUID REFERENCES paniers(id) ON DELETE CASCADE,
    item_id UUID,
    type_item VARCHAR(20),
    quantite INT
);

-- =========================
-- 14. COMMANDES
-- =========================
CREATE TABLE commandes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    utilisateur_id UUID REFERENCES utilisateurs(id) ON DELETE SET NULL,
    entreprise_id UUID REFERENCES entreprises(id) ON DELETE SET NULL,
    statut VARCHAR(30),
    prix_total DECIMAL(12,2),
    adresse_livraison TEXT,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    cree_le TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE commande_articles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    commande_id UUID REFERENCES commandes(id) ON DELETE CASCADE,
    item_id UUID,
    type_item VARCHAR(20),
    quantite INT,
    prix DECIMAL(12,2)
);

-- =========================
-- 15. LIVRAISONS
-- =========================
CREATE TABLE livraisons (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    commande_id UUID REFERENCES commandes(id) ON DELETE CASCADE,
    livreur_id UUID REFERENCES livreurs(id) ON DELETE SET NULL,
    statut VARCHAR(30),
    assigne_le TIMESTAMPTZ,
    livre_le TIMESTAMPTZ
);

-- =========================
-- 16. PAIEMENTS
-- =========================
CREATE TABLE paiements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    commande_id UUID REFERENCES commandes(id) ON DELETE CASCADE,
    montant DECIMAL(12,2),
    methode VARCHAR(50),
    statut VARCHAR(20),
    cree_le TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- 17. REMBOURSEMENTS
-- =========================
CREATE TABLE remboursements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    paiement_id UUID REFERENCES paiements(id) ON DELETE CASCADE,
    montant DECIMAL(12,2),
    raison TEXT,
    statut VARCHAR(20),
    cree_le TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- 18. PORTEFEUILLE (wallet)
-- =========================
CREATE TABLE portefeuilles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    utilisateur_id UUID REFERENCES utilisateurs(id) ON DELETE CASCADE,
    solde DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    portefeuille_id UUID REFERENCES portefeuilles(id) ON DELETE CASCADE,
    montant DECIMAL(12,2),
    type VARCHAR(20), -- debit / credit
    description TEXT,
    cree_le TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- 19. NOTIFICATIONS
-- =========================
CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    utilisateur_id UUID REFERENCES utilisateurs(id) ON DELETE CASCADE,
    titre VARCHAR(150),
    message TEXT,
    lu BOOLEAN DEFAULT false,
    cree_le TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- 20. FAVORIS
-- =========================
CREATE TABLE favoris (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    utilisateur_id UUID REFERENCES utilisateurs(id) ON DELETE CASCADE,
    entreprise_id UUID REFERENCES entreprises(id) ON DELETE CASCADE
);

-- =========================
-- 21. AVIS / NOTES
-- =========================
CREATE TABLE avis (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    utilisateur_id UUID REFERENCES utilisateurs(id) ON DELETE SET NULL,
    entreprise_id UUID REFERENCES entreprises(id) ON DELETE SET NULL,
    livreur_id UUID REFERENCES livreurs(id) ON DELETE SET NULL,
    note INT,
    commentaire TEXT
);

-- =========================
-- 22. PROMOTIONS
-- =========================
CREATE TABLE promotions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(50),
    reduction DECIMAL(5,2),
    expire_le TIMESTAMPTZ
);

CREATE TABLE commandes_promotions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    commande_id UUID REFERENCES commandes(id) ON DELETE CASCADE,
    promotion_id UUID REFERENCES promotions(id) ON DELETE CASCADE
);

-- =========================
-- 23. LOGS ADMIN
-- =========================
CREATE TABLE logs_admin (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    admin_id UUID REFERENCES utilisateurs(id) ON DELETE SET NULL,
    action TEXT,
    cree_le TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- 24. SESSIONS
-- =========================
CREATE TABLE sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    utilisateur_id UUID REFERENCES utilisateurs(id) ON DELETE CASCADE,
    token TEXT,
    expire_le TIMESTAMPTZ
);

-- =========================
-- 25. PARAMETRES APP
-- =========================
CREATE TABLE parametres (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cle VARCHAR(100),
    valeur TEXT
);